#+ method: GET
#+ summary: Query that retrieves all workflow templates and their label.

PREFIX opmw: <https://www.opmw.org/ontology/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT ?template ?label from <urn:x-arq:UnionGraph>
WHERE {
  ?template a opmw:WorkflowTemplate.
  ?template rdfs:label ?label
}