#+ method: GET
#+ summary: Query that gets all gets all intermediate and final results of an execution (and their labels)
#+ defaults:
#+   - exec: https://www.opmw.org/export/resource/WorkflowExecutionAccount/ClimComp_Precipi-90455b3a-0079-4a54-a444-a39fd1959e2b

PREFIX opmw: <https://www.opmw.org/ontology/>
PREFIX opmo: <http://openprovenance.org/model/opmo#>
PREFIX opmv: <http://purl.org/net/opmv/ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT ?result ?label from <urn:x-arq:UnionGraph>
WHERE {
  ?result a opmw:WorkflowExecutionArtifact.
  ?result rdfs:label ?label.
  ?result opmo:account ?_exec_iri.
  ?result opmv:wasGeneratedBy ?process.
  FILTER NOT EXISTS {?process2 opmv:used ?result}.
}
