#+ method: GET
#+ summary: Query that gets all inputs and parameters of an execution
#+ defaults:
#+   - exec: https://www.opmw.org/export/resource/WorkflowExecutionAccount/ClimComp_Precipi-90455b3a-0079-4a54-a444-a39fd1959e2b

PREFIX opmw: <https://www.opmw.org/ontology/>
PREFIX opmo: <http://openprovenance.org/model/opmo#>
PREFIX opmv: <http://purl.org/net/opmv/ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT ?input ?label from <urn:x-arq:UnionGraph>
WHERE {
  ?input a opmw:WorkflowExecutionArtifact.
  ?input rdfs:label ?label.
  ?input opmo:account ?_exec_iri.
  ?process1 opmv:used ?input.
  FILTER NOT EXISTS {?input opmv:wasGeneratedBy ?process2}.
}
