#+ method: GET
#+ summary: Query that gets all gets all results of an execution
#+ defaults:
#+   - exec: http://www.opmw.org/export/omics/resource/WorkflowExecutionAccount/ACCOUNT-ANALYZEAFFYDATA--E8F1AEA8-3BAD-4678-973F-121BCD197F28

PREFIX opmw: <http://www.opmw.org/ontology/>
PREFIX opmo: <http://openprovenance.org/model/opmo#>

SELECT ?result from <urn:x-arq:UnionGraph>
WHERE {
  ?result a opmw:WorkflowExecutionArtifact.
  ?result opmo:account ?_exec_iri.
}
