#+ method: GET
#+ summary: Query that gets all inputs and parameters of an execution
#+ defaults:
#+   - exec: http://www.opmw.org/export/resource/WorkflowExecutionAccount/Caesar_Cypher-1f-f788bcd8-75d9-4996-974d-ef6a442a36da

PREFIX opmw: <https://www.opmw.org/ontology/>
PREFIX opmo: <http://openprovenance.org/model/opmo#>
PREFIX opmv: <http://purl.org/net/opmv/ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT ?input ?label from <urn:x-arq:UnionGraph>
WHERE {
  ?input a opmw:WorkflowExecutionArtifact.
  ?input rdfs:label ?label.
  ?input opmo:account ?_exec_iri.
  ?process1 opmv:used ?input.
  FILTER NOT EXISTS {?input opmv:wasGeneratedBy ?process2}.
}
