#+ method: GET
#+ summary: gets all the activities of an execution.
#+ defaults:
#+   - exec: http://www.opmw.org/export/resource/WorkflowExecutionAccount/Caesar_Cypher-1f-f788bcd8-75d9-4996-974d-ef6a442a36da

PREFIX opmw: <http://www.opmw.org/ontology/>
PREFIX opmo: <http://openprovenance.org/model/opmo#>
PREFIX opmv: <http://purl.org/net/opmv/ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT ?process ?label from <urn:x-arq:UnionGraph>
WHERE {
  ?result a opmw:WorkflowExecutionArtifact.
  ?result opmo:account ?_exec_iri.
  ?result opmv:wasGeneratedBy ?process.
  ?process rdfs:label ?label.
}
