#+ endpoint: http://disk.isi.edu:3030/ds/query
#+ method: GET
#+ parameters:
#+ - name: templ
#+   in: query
#+   description: Template name
#+   required: true
#+   type: string
#+ summary: Query that retrieves all executions of a templat ?_templ and their status

PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT ?execution ?status from <urn:x-arq:UnionGraph>
WHERE {
  ?execution <http://www.opmw.org/ontology/correspondsToTemplate> ?_templ.
  ?execution <http://www.opmw.org/ontology/hasStatus> ?status
}
