#+ method: GET
#+ summary: Query that gets the dataset remote url of a execucion
#+ defaults:
#+   - exec: http://www.opmw.org/export/resource/WorkflowExecutionArtifact/Caesar_Cypher-f8-aa2fce2f-42ab-4b6c-9b89-e14ea8a56f7c_EncryptedDocument

PREFIX opmw: <http://www.opmw.org/ontology/>

SELECT ?result from <urn:x-arq:UnionGraph>
WHERE {
  ?_exec_iri opmw:hasLocation ?result 
}
