#+ method: GET
#+ summary: Query that gets the dataset remote url of a execucion
#+ defaults:
#+   - exec: https://www.opmw.org/export/resource/WorkflowExecutionAccount/SingleProteomicS-7eca5052-f1de-4ef5-a0b8-b383fa805293

PREFIX opmw: <https://www.opmw.org/ontology/>

SELECT ?result from <urn:x-arq:UnionGraph>
WHERE {
  ?_exec_iri opmw:hasLocation ?result 
}
