#+ method: GET
#+ summary: gets all inputs of a template and their metadata.
#+ defaults:
#+   - temp: https://www.opmw.org/export/resource/WorkflowTemplate/SingleProteomicS-6b54f310-0476-4fcb-a235-5fc0a68dd4c7_v1

PREFIX opmw: <https://www.opmw.org/ontology/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT ?input ?prop ?value from <urn:x-arq:UnionGraph>
WHERE {
  ?input a opmw:WorkflowTemplateArtifact.
  ?input opmw:isVariableOfTemplate ?_temp_iri.
  ?input ?prop ?value.
  ?process1 opmw:uses ?input.
  FILTER NOT EXISTS {?input opmw:isGeneratedBy ?process2}.
}
