#+ method: GET
#+ summary: gets all inputs of a template and their metadata.
#+ defaults:
#+   - temp: http://www.opmw.org/export/omics/resource/WorkflowTemplate/ANALYZEAFFYDATA-D751713988987E9331980363E24189CE

PREFIX opmw: <http://www.opmw.org/ontology/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT ?input ?prop ?value from <urn:x-arq:UnionGraph>
WHERE {
  ?input a opmw:WorkflowTemplateArtifact.
  ?input opmw:isVariableOfTemplate ?_temp_iri.
  ?input ?prop ?value.
  ?process1 opmw:uses ?input.
  FILTER NOT EXISTS {?input opmw:isGeneratedBy ?process2}.
}
