#+ method: GET
#+ summary: gets all outputs of a template and their metadata.
#+ defaults:
#+   - temp: http://www.opmw.org/export/omics/resource/WorkflowTemplate/ANALYZEAFFYDATA-D751713988987E9331980363E24189CE

PREFIX opmw: <https://www.opmw.org/ontology/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT ?output ?prop ?value from <urn:x-arq:UnionGraph>
WHERE {
  ?output a opmw:WorkflowTemplateArtifact.
  ?output opmw:isVariableOfTemplate ?_temp_iri.
  ?output ?prop ?value.
  ?output opmw:isGeneratedBy ?process.
  FILTER NOT EXISTS {?process2 opmw:uses ?output}.
}
