#+ method: GET
#+ summary: gets all steps of a template and their metadata.
#+ defaults:
#+   - temp: https://www.opmw.org/export/resource/WorkflowTemplate/SingleProteomicS-6b54f310-0476-4fcb-a235-5fc0a68dd4c7_v1

PREFIX opmw: <https://www.opmw.org/ontology/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT ?step ?prop ?value from <urn:x-arq:UnionGraph>
WHERE {
  ?step a opmw:WorkflowTemplateProcess.
  ?step opmw:isStepOfTemplate ?_temp_iri.
  ?step ?prop ?value.
}