#+ method: GET
#+ summary: gets the template that was executed to produce the target execution.
#+ defaults:
#+   - exec: http://www.opmw.org/export/resource/WorkflowExecutionAccount/Caesar_Cypher-1f-f788bcd8-75d9-4996-974d-ef6a442a36da

PREFIX opmw: <http://www.opmw.org/ontology/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT ?template ?label from <urn:x-arq:UnionGraph>
WHERE {
  ?template a opmw:WorkflowTemplate.
  ?template rdfs:label ?label.
  ?_exec_iri opmw:correspondsToTemplate ?template.
}
