#+ method: GET
#+ summary: TO DO - gets the template that was executed to produce the target execution.
#+ defaults:
#+   - exec:TO ADD

PREFIX opmw: <http://www.opmw.org/ontology/>

SELECT ?execution ?status from <urn:x-arq:UnionGraph>
WHERE {
  #TO DO
}
