#+ method: GET
#+ summary: gets the template that was executed to produce the target execution.
#+ defaults:
#+   - exec: http://www.opmw.org/export/omics/resource/WorkflowExecutionAccount/ACCOUNT-ANALYZEAFFYDATA--E8F1AEA8-3BAD-4678-973F-121BCD197F28

PREFIX opmw: <http://www.opmw.org/ontology/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT ?template ?label from <urn:x-arq:UnionGraph>
WHERE {
  ?template a opmw:WorkflowTemplate.
  ?template rdfs:label ?label.
  ?_exec_iri a opmw:WorkflowExecutionAccount.
  ?_exec_iri opmw:correspondsToTemplate ?template.
}
