#+ method: GET
#+ summary: gets all outputs of a template and their metadata.
#+ defaults:
#+   - temp: https://www.opmw.org/export/resource/WorkflowTemplate/SingleProteomicS-6b54f310-0476-4fcb-a235-5fc0a68dd4c7_v1

PREFIX opmw: <https://www.opmw.org/ontology/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT ?output ?prop ?value from <urn:x-arq:UnionGraph>
WHERE {
  ?output a opmw:WorkflowTemplateArtifact.
  ?output opmw:isVariableOfTemplate ?_temp_iri.
  ?output ?prop ?value.
  ?output opmw:isGeneratedBy ?process.
  FILTER NOT EXISTS {?process2 opmw:uses ?output}.
}
